source :rubygems

gem 'rails', '>= 3.2.11'
gem 'pg'

gem 'active_shipping'
gem 'addressable'
gem 'bodega', '>= 0.4.8', git: 'https://github.com/flipsasser/bodega.git'
gem 'carrierwave', '0.7.1'
gem 'rmagick'
gem 'numbers_and_words'
gem 'paypal-express'

group :assets do
  gem 'less-rails'
  gem 'therubyracer', '0.10.2', platforms: :ruby
  gem 'uglifier', '>= 1.0.3'
end

group :production do
  gem 'fog', '~> 1.3.1'
end
